### PR TITLE
fixing leaked global variable

### PR DESCRIPTION
**Pull request by stevenmiller888**
@calvinfo

### CODE REVIEW

**Comment by calvinfo** [comment]
that's weird, why do the tests fail? otherwise, lgtm!

**Comment by calvinfo** [comment]
oh, can you also add `make-lint` so it catches the global thing? 

https://github.com/tj/make-lint

**Comment by stevenmiller888** [comment]
@calvinfo Should be good to go now :)

**Comment by calvinfo** [comment]
kwaboosh! ship it!

**Pull request merged**
